### PR TITLE
ES2015ify codebase

### PR DESCRIPTION
**Pull request by LinusU**
Following sindresorhus/write-json-file#5, here is an update for this module as well :)

### CODE REVIEW

**Comment by SamVerschueren** [comment]
I would write them on one line

**Comment by LinusU** [comment]
Done 👌

**Comment by SamVerschueren** [comment]
Update the node engine to `>4`

**Comment by LinusU** [comment]
Done 👌

**Comment by SamVerschueren** [comment]
LGTM

**Comment by sindresorhus** [comment]
Thanks :)

**Comment by LinusU** [comment]
Thank you 👌

**Pull request merged**
